FROM nginx:1.21-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY ./media-editor.crt /etc/ssl/
COPY ./media-editor.key /etc/ssl/

COPY . /etc/nginx/
COPY ./nginx/nginx-prod.conf /etc/nginx/nginx.conf
